'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class Settings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As Settings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New Settings()),Settings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As Settings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Startup() As Boolean
        Get
            Return CType(Me("Startup"),Boolean)
        End Get
        Set
            Me("Startup") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Minimized() As Boolean
        Get
            Return CType(Me("Minimized"),Boolean)
        End Get
        Set
            Me("Minimized") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property CloseAfterClean() As Boolean
        Get
            Return CType(Me("CloseAfterClean"),Boolean)
        End Get
        Set
            Me("CloseAfterClean") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ShowReadOnly() As Boolean
        Get
            Return CType(Me("ShowReadOnly"),Boolean)
        End Get
        Set
            Me("ShowReadOnly") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ThumbnailCache() As Boolean
        Get
            Return CType(Me("ThumbnailCache"),Boolean)
        End Get
        Set
            Me("ThumbnailCache") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property MiniDumps() As Boolean
        Get
            Return CType(Me("MiniDumps"),Boolean)
        End Get
        Set
            Me("MiniDumps") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property TemporaryFiles() As Boolean
        Get
            Return CType(Me("TemporaryFiles"),Boolean)
        End Get
        Set
            Me("TemporaryFiles") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property RecycleBin() As Boolean
        Get
            Return CType(Me("RecycleBin"),Boolean)
        End Get
        Set
            Me("RecycleBin") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property TempFiles() As Boolean
        Get
            Return CType(Me("TempFiles"),Boolean)
        End Get
        Set
            Me("TempFiles") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property MemoryDumps() As Boolean
        Get
            Return CType(Me("MemoryDumps"),Boolean)
        End Get
        Set
            Me("MemoryDumps") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property EventTraceLogs() As Boolean
        Get
            Return CType(Me("EventTraceLogs"),Boolean)
        End Get
        Set
            Me("EventTraceLogs") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ErrorReporting() As Boolean
        Get
            Return CType(Me("ErrorReporting"),Boolean)
        End Get
        Set
            Me("ErrorReporting") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property DriverInstallation() As Boolean
        Get
            Return CType(Me("DriverInstallation"),Boolean)
        End Get
        Set
            Me("DriverInstallation") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property DeliveryOpti() As Boolean
        Get
            Return CType(Me("DeliveryOpti"),Boolean)
        End Get
        Set
            Me("DeliveryOpti") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property NetworkData() As Boolean
        Get
            Return CType(Me("NetworkData"),Boolean)
        End Get
        Set
            Me("NetworkData") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property WindowsLogs() As Boolean
        Get
            Return CType(Me("WindowsLogs"),Boolean)
        End Get
        Set
            Me("WindowsLogs") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Prefetch() As Boolean
        Get
            Return CType(Me("Prefetch"),Boolean)
        End Get
        Set
            Me("Prefetch") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property StoreInstallServiceCache() As Boolean
        Get
            Return CType(Me("StoreInstallServiceCache"),Boolean)
        End Get
        Set
            Me("StoreInstallServiceCache") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property QtFramework() As Boolean
        Get
            Return CType(Me("QtFramework"),Boolean)
        End Get
        Set
            Me("QtFramework") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property PowerEfficencyDiagnostics() As Boolean
        Get
            Return CType(Me("PowerEfficencyDiagnostics"),Boolean)
        End Get
        Set
            Me("PowerEfficencyDiagnostics") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Notfications() As Boolean
        Get
            Return CType(Me("Notfications"),Boolean)
        End Get
        Set
            Me("Notfications") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property MsSearch() As Boolean
        Get
            Return CType(Me("MsSearch"),Boolean)
        End Get
        Set
            Me("MsSearch") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property JumpList() As Boolean
        Get
            Return CType(Me("JumpList"),Boolean)
        End Get
        Set
            Me("JumpList") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property FontCache() As Boolean
        Get
            Return CType(Me("FontCache"),Boolean)
        End Get
        Set
            Me("FontCache") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property WinDefender() As Boolean
        Get
            Return CType(Me("WinDefender"),Boolean)
        End Get
        Set
            Me("WinDefender") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property OriginInstaller() As Boolean
        Get
            Return CType(Me("OriginInstaller"),Boolean)
        End Get
        Set
            Me("OriginInstaller") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property VisualStudio() As Boolean
        Get
            Return CType(Me("VisualStudio"),Boolean)
        End Get
        Set
            Me("VisualStudio") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property OneDrive() As Boolean
        Get
            Return CType(Me("OneDrive"),Boolean)
        End Get
        Set
            Me("OneDrive") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property EasyAntiCheat() As Boolean
        Get
            Return CType(Me("EasyAntiCheat"),Boolean)
        End Get
        Set
            Me("EasyAntiCheat") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Battlenet() As Boolean
        Get
            Return CType(Me("Battlenet"),Boolean)
        End Get
        Set
            Me("Battlenet") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Ccleaner() As Boolean
        Get
            Return CType(Me("Ccleaner"),Boolean)
        End Get
        Set
            Me("Ccleaner") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property Steam() As Boolean
        Get
            Return CType(Me("Steam"),Boolean)
        End Get
        Set
            Me("Steam") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property DirectX() As Boolean
        Get
            Return CType(Me("DirectX"),Boolean)
        End Get
        Set
            Me("DirectX") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property WinUpdateFiles() As Boolean
        Get
            Return CType(Me("WinUpdateFiles"),Boolean)
        End Get
        Set
            Me("WinUpdateFiles") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property WinFontCache() As Boolean
        Get
            Return CType(Me("WinFontCache"),Boolean)
        End Get
        Set
            Me("WinFontCache") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property WinDebug() As Boolean
        Get
            Return CType(Me("WinDebug"),Boolean)
        End Get
        Set
            Me("WinDebug") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property WinCache() As Boolean
        Get
            Return CType(Me("WinCache"),Boolean)
        End Get
        Set
            Me("WinCache") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property WinInstaller() As Boolean
        Get
            Return CType(Me("WinInstaller"),Boolean)
        End Get
        Set
            Me("WinInstaller") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property WinExpIndex() As Boolean
        Get
            Return CType(Me("WinExpIndex"),Boolean)
        End Get
        Set
            Me("WinExpIndex") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property WinAutoVideo() As Boolean
        Get
            Return CType(Me("WinAutoVideo"),Boolean)
        End Get
        Set
            Me("WinAutoVideo") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property RecentDocuments() As Boolean
        Get
            Return CType(Me("RecentDocuments"),Boolean)
        End Get
        Set
            Me("RecentDocuments") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property EdgeCache() As Boolean
        Get
            Return CType(Me("EdgeCache"),Boolean)
        End Get
        Set
            Me("EdgeCache") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property EdgeCookies() As Boolean
        Get
            Return CType(Me("EdgeCookies"),Boolean)
        End Get
        Set
            Me("EdgeCookies") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property EdgeHistory() As Boolean
        Get
            Return CType(Me("EdgeHistory"),Boolean)
        End Get
        Set
            Me("EdgeHistory") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property EdgeSession() As Boolean
        Get
            Return CType(Me("EdgeSession"),Boolean)
        End Get
        Set
            Me("EdgeSession") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property EdgePasswords() As Boolean
        Get
            Return CType(Me("EdgePasswords"),Boolean)
        End Get
        Set
            Me("EdgePasswords") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property EdgeMetrics() As Boolean
        Get
            Return CType(Me("EdgeMetrics"),Boolean)
        End Get
        Set
            Me("EdgeMetrics") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ChromeCache() As Boolean
        Get
            Return CType(Me("ChromeCache"),Boolean)
        End Get
        Set
            Me("ChromeCache") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ChromeHistroy() As Boolean
        Get
            Return CType(Me("ChromeHistroy"),Boolean)
        End Get
        Set
            Me("ChromeHistroy") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ChromeCookies() As Boolean
        Get
            Return CType(Me("ChromeCookies"),Boolean)
        End Get
        Set
            Me("ChromeCookies") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ChromeDownloadHistory() As Boolean
        Get
            Return CType(Me("ChromeDownloadHistory"),Boolean)
        End Get
        Set
            Me("ChromeDownloadHistory") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ChromeMetrics() As Boolean
        Get
            Return CType(Me("ChromeMetrics"),Boolean)
        End Get
        Set
            Me("ChromeMetrics") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ChromeSession() As Boolean
        Get
            Return CType(Me("ChromeSession"),Boolean)
        End Get
        Set
            Me("ChromeSession") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ChromePasswords() As Boolean
        Get
            Return CType(Me("ChromePasswords"),Boolean)
        End Get
        Set
            Me("ChromePasswords") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ShowChrome() As Boolean
        Get
            Return CType(Me("ShowChrome"),Boolean)
        End Get
        Set
            Me("ShowChrome") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ShowFirefox() As Boolean
        Get
            Return CType(Me("ShowFirefox"),Boolean)
        End Get
        Set
            Me("ShowFirefox") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ShowEdge() As Boolean
        Get
            Return CType(Me("ShowEdge"),Boolean)
        End Get
        Set
            Me("ShowEdge") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ExpandAll() As Boolean
        Get
            Return CType(Me("ExpandAll"),Boolean)
        End Get
        Set
            Me("ExpandAll") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ShowWindows() As Boolean
        Get
            Return CType(Me("ShowWindows"),Boolean)
        End Get
        Set
            Me("ShowWindows") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ShowAdvanced() As Boolean
        Get
            Return CType(Me("ShowAdvanced"),Boolean)
        End Get
        Set
            Me("ShowAdvanced") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ShowApps() As Boolean
        Get
            Return CType(Me("ShowApps"),Boolean)
        End Get
        Set
            Me("ShowApps") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property FirefoxCache() As Boolean
        Get
            Return CType(Me("FirefoxCache"),Boolean)
        End Get
        Set
            Me("FirefoxCache") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property FirefoxHistory() As Boolean
        Get
            Return CType(Me("FirefoxHistory"),Boolean)
        End Get
        Set
            Me("FirefoxHistory") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property FirefoxCookies() As Boolean
        Get
            Return CType(Me("FirefoxCookies"),Boolean)
        End Get
        Set
            Me("FirefoxCookies") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property FirefoxSession() As Boolean
        Get
            Return CType(Me("FirefoxSession"),Boolean)
        End Get
        Set
            Me("FirefoxSession") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property FirefoxSite() As Boolean
        Get
            Return CType(Me("FirefoxSite"),Boolean)
        End Get
        Set
            Me("FirefoxSite") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property FirefoxForm() As Boolean
        Get
            Return CType(Me("FirefoxForm"),Boolean)
        End Get
        Set
            Me("FirefoxForm") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property FirefoxPasswords() As Boolean
        Get
            Return CType(Me("FirefoxPasswords"),Boolean)
        End Get
        Set
            Me("FirefoxPasswords") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property FirefoxPath() As String
        Get
            Return CType(Me("FirefoxPath"),String)
        End Get
        Set
            Me("FirefoxPath") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property InternetExplorer() As Boolean
        Get
            Return CType(Me("InternetExplorer"),Boolean)
        End Get
        Set
            Me("InternetExplorer") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Sid() As String
        Get
            Return CType(Me("Sid"),String)
        End Get
        Set
            Me("Sid") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Windows() As String
        Get
            Return CType(Me("Windows"),String)
        End Get
        Set
            Me("Windows") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Gpu() As String
        Get
            Return CType(Me("Gpu"),String)
        End Get
        Set
            Me("Gpu") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Cpu() As String
        Get
            Return CType(Me("Cpu"),String)
        End Get
        Set
            Me("Cpu") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Ram() As String
        Get
            Return CType(Me("Ram"),String)
        End Get
        Set
            Me("Ram") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Settings
            Get
                Return Global.Settings.Default
            End Get
        End Property
    End Module
End Namespace
